# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Odyssee Productions
description: > # this means to ignore newlines until "baseurl:"
  Open Collective gathering journalists, graphic designers, cinematographers and musicians, 
  producing social & cultural documentaries, crowdsourcing its info-gathering in order to 
  provide raw & unfiltered content.
# CHANGE THIS WHEN DEPLOYING 
baseurl: "" # the subpath of your site, e.g. /blog
# /odyssee    FOR PRODUCTION
# /           FOR DEVELOPMENT

url: "http://odysseeproduction.com/" # the base hostname & protocol for your site
# https://unless-io.github.io     FOR PRODUCTION 
# http://localhost:4000           FOR DEVELOPMENT

email: "hi@odysseeproduction.com"
phone: "+32.494/06.77.55"
facebook: "https://www.facebook.com/odysseeproduction"
instagram: "https://www.instagram.com/odysseeprod/"
location: "Brussels, Belgium"
logo: "http://odysseeproduction.com/images/logo_rond.png"

collections:
- team_members

# Build settings
markdown: kramdown

meta:
  geo_placename: Brussels
  geo_position: "50.8386162;4.2233225"
  geo_region: BE

  name: Odyssee Production
  description: 
    Open Collective gathering journalists, graphic designers, cinematographers and musicians, 
    producing social & cultural documentaries, crowdsourcing its info-gathering in order to 
    provide raw & unfiltered content.
  image: "http://odysseeproduction.com/images/animation.gif"

  fb_site_name: Odyssee Production
  fb_title: Odyssee Production - Open Collective
  fb_description: 
    Open Collective gathering journalists, graphic designers, cinematographers and musicians, 
    producing social & cultural documentaries, crowdsourcing its info-gathering in order to 
    provide raw & unfiltered content.
  fb_image: "http://odysseeproduction.com/images/animation.gif"
  fb_type: Website
  fb_url: http://odysseeproduction.com/

  google_name: Odyssee Production
  google_description: 
    Open Collective gathering journalists, graphic designers, cinematographers and musicians, 
    producing social & cultural documentaries, crowdsourcing its info-gathering in order to 
    provide raw & unfiltered content.
  google_image: "http://odysseeproduction.com/images/animation.gif"

  twitter_card_type: summary_large_image
  twitter_title: Odyssee Production - Open Collective
  twitter_description: 
    Open Collective gathering journalists, graphic designers, cinematographers and musicians, 
    producing social & cultural documentaries, crowdsourcing its info-gathering in order to 
    provide raw & unfiltered content.


navigation_items:
  home: /
  project: project
  team: team
  blog: blog
  "help us": help
  contact: contact